# Site settings
title: TryHomeo.com | Delivering the best in Homeopathy.
description: "Our clinic delivers the best in Homeopathy."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tryhomeo.com" # the name of your domain
logo_url: img/logo2.png
site_name: TryHomeo.com

# Hero
hero: 
    hero_img: hero9-min.png
    hero_title: TryHomeo
    hero_description: Delivering the best in Homeopathy.

# Contact form
api_token: a91bda7d8c8742db5a154e162f4ed020

# Contact info
contact:
    phone: +91 8144009060
    emergency: +91 431 2514140
    email: doctor@tryhomeo.com
    address: A-124, JaiNagar, Thiruverambur, Trichy - 620013, Tamil Nadu, INDIA

# Opening hours
monday_friday: 10:00 – 20:00
saturday: 10:00 – 20:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address : "Dr. R Ramasamy A-124, Jai Nagar Thiruverumbur"
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/tryhomeo
twitter: http://twitter.com/tryhomeo
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 TryHomeo - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    vendor
]

# Theme Settings
analytics: "UA-5456627-2"
google_verification: "Mek1L3OzeZBBNiNvCYdXvKvjmKko9LwAMAeQiFE4j_g"
